AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Parameters:
  StageName:
    Type: String
    Default: dev
  FunctionName:
    Type: String
    Default: serverless_app_user_java
Mappings:
  RegionMap:
    us-west-2:
      S3Bucket: ghx-deployment-or
      S3Key: serverless-app-poc/serverless_app/serverless-app-0.0.1-SNAPSHOT.jar
      role: lambda_s3_vpc_execution
      SecurityGroupIds:
      - sg-06f6e964
      SubnetIds:
      - subnet-72c7d206
      - subnet-3b192d7d
      - subnet-821aefe7
Resources:
  ApiGatewayApi:
   Type: AWS::Serverless::Api
   Properties:
      StageName: !Ref StageName
      DefinitionBody:
        swagger: '2.0'
        info:
          version: '1.0'
          title: serverlessapi
          description: Serverless API
        schemes:
        - https
        paths:
          "/clincx/v1/user":
            get:
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
                  schema:
                    "$ref": "#/definitions/Empty"
              security:
              - sso-authentication: []
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: '200'
                requestTemplates:
                  application/json: |-
                    {
                        "stage": "$context.stage"
                    }
                uri:
                  Fn::Join:
                  - ''
                  - - 'arn:aws:apigateway:'
                    - Ref: AWS::Region
                    - ":lambda:path/2015-03-31/functions/"
                    - Fn::Join:
                      - ''
                      - - 'arn:aws:lambda:'
                        - Ref: AWS::Region
                        - ":"
                        - Ref: AWS::AccountId
                        - ":function:!Ref FunctionName"
                    - "/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                credentials:
                  Fn::Join:
                  - ''
                  - - 'arn:aws:iam::'
                    - Ref: AWS::AccountId
                    - ":role/clincx-gateway-awsservices"
                contentHandling: CONVERT_TO_TEXT
                type: aws
        securityDefinitions:
          sso-authentication:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: custom
            x-amazon-apigateway-authorizer:
              authorizerUri:
                Fn::Join:
                - ''
                - - 'arn:aws:apigateway:'
                  - Ref: AWS::Region
                  - ":lambda:path/2015-03-31/functions/"
                  - Fn::Join:
                    - ''
                    - - 'arn:aws:lambda:'
                      - Ref: AWS::Region
                      - ":"
                      - Ref: AWS::AccountId
                      - ":function:clincx_sso"
                  - "/invocations"
              authorizerResultTtlInSeconds: 0
              authorizerCredentials:
                Fn::Join:
                - ''
                - - 'arn:aws:iam::'
                  - Ref: AWS::AccountId
                  - ":role/clincx-gateway-awsservices"
              type: token
        definitions:
          Empty:
            type: object
            title: Empty Schema          
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::FindInMap:
          - RegionMap
          - Ref: AWS::Region
          - S3Bucket
        S3Key:
          Fn::FindInMap:
          - RegionMap
          - Ref: AWS::Region
          - S3Key
      Description: 'Return all users'
      FunctionName: !Ref FunctionName
      Handler: com.test.api.admin.user.User::handleRequest
      MemorySize: 512
      Role:
        Fn::Join:
        - ''
        - - 'arn:aws:iam::'
          - Ref: AWS::AccountId
          - ":role/"
          - Fn::FindInMap:
            - RegionMap
            - Ref: AWS::Region
            - role
      Runtime: java8
      Timeout: '120'
      VpcConfig:
        SecurityGroupIds:
          Fn::FindInMap:
          - RegionMap
          - Ref: AWS::Region
          - SecurityGroupIds
        SubnetIds:
          Fn::FindInMap:
          - RegionMap
          - Ref: AWS::Region
          - SubnetIds
