AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  serverlessapi:
   Type: AWS::Serverless::Api
   Properties:
      StageName: dev
      DefinitionUri: ./serverless_app_swagger.yaml
  serverlessuser:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'com.test.api.admin.user.User::handleRequest'
      Runtime: java8
      FunctionName: serverless_app_user_java
      CodeUri: ./serverless-app-0.0.1-SNAPSHOT.jar
      Description: ''
      MemorySize: 512
      Timeout: 300
      Role: 'arn:aws:iam::050190852521:role/lambda_s3_vpc_execution'
      VpcConfig:
        SecurityGroupIds:
          - sg-c58bdfb8
        SubnetIds:
          - subnet-72c7d206
          - subnet-821aefe7
          - subnet-3b192d7d
