AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  ApiGatewayApi:
   Type: AWS::Serverless::Api
   Properties:
      StageName: dev
      DefinitionBody:
        swagger: '2.0'
        info:
          version: '1.0'
          title: serverlessapi
          description: Serverless API
        schemes:
        - https
        paths:
          "/clincx/v1/user":
            get:
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
                  schema:
                    "$ref": "#/definitions/Empty"
              security:
              - sso-authentication: []
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: '200'
                requestTemplates:
                  application/json: |-
                    {
                        "stage": "$context.stage"
                    }
                uri:
                  Fn::Join:
                  - ''
                  - - 'arn:aws:apigateway:'
                    - Ref: AWS::Region
                    - ":lambda:path/2015-03-31/functions/"
                    - Fn::Join:
                      - ''
                      - - 'arn:aws:lambda:'
                        - Ref: AWS::Region
                        - ":"
                        - Ref: AWS::AccountId
                        - ":function:serverless_app_user_java"
                    - "/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                credentials:
                  Fn::Join:
                  - ''
                  - - 'arn:aws:iam::'
                    - Ref: AWS::AccountId
                    - ":role/clincx-gateway-awsservices"
                contentHandling: CONVERT_TO_TEXT
                type: aws
        securityDefinitions:
          sso-authentication:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: custom
            x-amazon-apigateway-authorizer:
              authorizerUri:
                Fn::Join:
                - ''
                - - 'arn:aws:apigateway:'
                  - Ref: AWS::Region
                  - ":lambda:path/2015-03-31/functions/"
                  - Fn::Join:
                    - ''
                    - - 'arn:aws:lambda:'
                      - Ref: AWS::Region
                      - ":"
                      - Ref: AWS::AccountId
                      - ":function:clincx_sso"
                  - "/invocations"
              authorizerResultTtlInSeconds: 0
              authorizerCredentials:
                Fn::Join:
                - ''
                - - 'arn:aws:iam::'
                  - Ref: AWS::AccountId
                  - ":role/clincx-gateway-awsservices"
              type: token
        definitions:
          Empty:
            type: object
            title: Empty Schema        
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'com.test.api.admin.user.User::handleRequest'
      Runtime: java8
      FunctionName: serverless_app_user_java
      CodeUri: 's3://ghx-deployment-or/serverless-app-poc/serverless_app/serverless-app-0.0.1-SNAPSHOT.jar'
      Description: ''
      MemorySize: 512
      Timeout: 300
      Role: 'arn:aws:iam::050190852521:role/lambda_s3_vpc_execution'
      VpcConfig:
        SecurityGroupIds:
          - sg-c58bdfb8
        SubnetIds:
          - subnet-72c7d206
          - subnet-821aefe7
          - subnet-3b192d7d